name: Changelog

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  heylogs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check CHANGELOG.md with heylogs
        uses: jbangdev/jbang-action@v0.142.0
        with:
          script: com.github.nbbrd.heylogs:heylogs-cli:0.19.1:bin
          scriptargs: "check CHANGELOG.md --format github-actions"
